# 部署时, 将 `application.yml` 放于与 Jar 同级目录的 `config` 子目录下
server:
  # HTTP 服务端口
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wxj_demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: ENC(LpKzxIRAC8loqqubNPQ/mH07CsDTsTROMYxMYT/VLAoa1I/cpsjaXPtUGOjZBTVq)
    password: ENC(/9DkUYAc8auCdnlhpujcURcpgxSm1EJ+lyANKftQEh3kFdUbp1+briiZvU7rCrXe)
    hikari:
      connection-timeout: 30_000
      maximum-pool-size: 10
      idle-timeout: 600_000
      max-lifetime: 28795_000
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    banner-mode: off
  # Spring Security 默认用户名密码配置，无实际用途，仅仅为了去除 WARN Log
  security:
    user:
      name: user
      password: $2a$10$IPnO6FAD04p5TnYvDvNqn.5A4ZIG9T.0j6GMK3pqkeDoB0ooP1wP.
mybatis:
  type-handlers-package: net.wuxianjie.springbootweb.shared.mybatis
  mapper-locations: classpath:**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    shrink-whitespaces-in-sql: true
    # 打印 MyBatis SQL，生产环境下请注释掉
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
auth:
  token-key: '=rgd(B`]{Q\4fRA'
# 打印 JPA SQL 及参数值
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
